from pathlib import Path
import os

_basedir = Path(workflow.basedir).resolve()
REPO_ROOT = _basedir.parent if _basedir.name == "workflow" else _basedir

configfile: str(REPO_ROOT / "workflow" / "config.yaml")

PHD_DATA = Path(config["phd_data_root"])
CHAPTER = PHD_DATA / "Chapter_waste"
FIG = REPO_ROOT / "Figure"

PREP = CHAPTER / "1prepare_chapter_data"
COV = CHAPTER / "2coverage_analysis"
GRID100 = CHAPTER / "3_100m"
EXT = CHAPTER / "0_extend_grid"
CMP = CHAPTER / "4_compare"
PAT = CHAPTER / "5_spatial_pattern"

H3_RES = int(config.get("h3_res", 8))
ROAD_BUF = int(config.get("road_buffer_m", 50))
SVI_BUFFERS = [int(b) for b in config.get("svi_buffers_m", [50, 75, 100])]
INCLUDE_OSMNX = bool(config.get("include_osmnx", True))
USE_EXTENDED = bool(config.get("use_extended_grid", True))
USE_EXTENDED_FLAG = "1" if USE_EXTENDED else "0"
CITYROAD_TAG = f"h3_res{H3_RES}_buf{ROAD_BUF}m"

os.environ["PHD_DATA_ROOT"] = str(PHD_DATA)
os.environ["USE_EXTENDED_GRID"] = USE_EXTENDED_FLAG
os.environ["PYTHONPATH"] = str(REPO_ROOT) + (
    os.pathsep + os.environ["PYTHONPATH"] if os.environ.get("PYTHONPATH") else ""
)
# Quadruple-brace PYTHONPATH so Snakemake emits ${PYTHONPATH:-} for bash.
shell.prefix('export PYTHONPATH="' + str(REPO_ROOT) + '":"${{PYTHONPATH:-}}"; ')

wildcard_constraints:
    buffer=r"[0-9]+",


def roadsvi_figdir(buffer):
    if int(buffer) == 50:
        return FIG / "2coverage_analysis"
    return FIG / "2coverage_analysis" / "buffer"


include: "rules/01_prepare.smk"
include: "rules/00_extend_grid.smk"
include: "rules/02_coverage.smk"
include: "rules/03_grid.smk"
include: "rules/04_compare.smk"
include: "rules/05_spatial.smk"


def _all_data():
    files = list(PREPARE_DATA) + list(COVERAGE_DATA) + list(GRID_DATA) + list(COMPARE_DATA) + list(SPATIAL_DATA)
    if USE_EXTENDED:
        files += list(EXTEND_DATA)
    if INCLUDE_OSMNX:
        files += list(OSMNX_DATA)
    return files


def _all_figures():
    files = list(PREPARE_FIGS) + list(COVERAGE_FIGS) + list(GRID_FIGS) + list(COMPARE_FIGS) + list(SPATIAL_FIGS)
    if USE_EXTENDED:
        files += list(EXTEND_FIGS)
    if INCLUDE_OSMNX:
        files += list(OSMNX_FIGS)
    return files


rule all:
    input:
        _all_data() + _all_figures(),


rule all_data:
    input:
        _all_data(),


rule all_figures:
    input:
        _all_figures(),


rule dag:
    output:
        FIG / "workflow" / "spatial_rulegraph.pdf"
    shell:
        "bash {REPO_ROOT}/workflow/export_dag.sh"
